console.log("Trying to understand regex in javascript");
const re=/ab+c/;
const reg=new RegExp("ab+c");
const pattern=/hello/;
// const result=pattern.test("hello world");
const result=pattern.test("world");
console.log("Is there a match in the pattern",result);
const pattarn=/\d+/;
const resalt=pattarn.exec("The price is 100");
console.log(resalt);
const text="hello world";
const patani=/o/g;
const resalti=text.match(patani);
console.log("The .match results is",resalti);
const texti="oranges, banana, mangoes";
console.log("Unreplaced text is==>",texti);
const pettern=/banana/;
const risult=texti.replace(pettern,"apple");
console.log("The replaced text result is==>",risult);
const hello="Hello world";
// const filter=/hello/i;
const filter=/hello/;
const getResult=hello.match(filter);
console.log("Not case sensitive==>",getResult);
const checkPattern=/^start.*string$/mg;
const stringText='start by checking string\nstart line string';
const checkResult=stringText.match(checkPattern);
console.log("The m flag returns==>",checkResult);
